rolling_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint1
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint2
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint3
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint4
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint5
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint6
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint7
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint8
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint9
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint10_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint10
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint11_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint11
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint12_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint12
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint13_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint13
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint14_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint14
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint15_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint15
    pid: {p: 1500.0, i: 100.0, d: 100.0}
  joint16_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint16
    pid: {p: 1500.0, i: 100.0, d: 100.0}
